version: "3.8"
services:
  client:
    build:
      context: ./toneallyfe
      dockerfile: Dockerfile.dev
    command: yarn start
    volumes:
      - ./toneallyfe/src:/app/src
      - ./toneallyfe/public:/app/public
      - ./toneallyfe/package.json:/app/package.json
      - ./toneallyfe/yarn.lock:/app/yarn.lock
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - WATCHPACK_POLLING=true
    depends_on:
      - server

  server:
    build:
      context: ./toneallybe
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./toneallybe:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
